Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy, pull requests merged in 2021-04, with the labels that each got.

#145 Implementation of swipe function and update of delete dialogs
  BibBuddy/app/build.gradle
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SwipeToDeleteCallback.java
  BibBuddy/app/src/main/res/drawable/ic_delete.xml
  BibBuddy/app/src/main/res/drawable/ic_edit.xml
  BibBuddy/app/src/main/res/layout/fragment_author.xml
  BibBuddy/app/src/main/res/layout/fragment_book.xml
  BibBuddy/app/src/main/res/layout/fragment_book_notes.xml
  BibBuddy/app/src/main/res/layout/fragment_library.xml
  BibBuddy/app/src/main/res/layout/fragment_library_add_shelf.xml
  BibBuddy/app/src/main/res/layout/fragment_notes.xml
  BibBuddy/app/src/main/res/values/colors.xml
  BibBuddy/app/src/main/res/values/strings.xml
  BibBuddy/gradle/wrapper/gradle-wrapper.properties
Labels: Design

#149 Fix and clean note related features
  BibBuddy/app/src/main/java/de/bibbuddy/DateConverter.java
  BibBuddy/app/src/main/java/de/bibbuddy/Note.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteAudioItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditor.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorBulletSpan.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorPart.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorQuoteSpan.java
  BibBuddy/app/src/main/java/de/bibbuddy/SeekBarListener.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/VoiceNoteEditorFragment.java
  BibBuddy/app/src/main/res/layout/fragment_text_note_editor.xml
Labels: Bugfix, Multimedia

#150 Create Library Form for shelf (see Issue #100)
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryAddShelfFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRenameShelfFragment.java
  BibBuddy/app/src/main/res/layout/fragment_library_add_shelf.xml
  BibBuddy/app/src/main/res/layout/fragment_library_form.xml
  BibBuddy/app/src/main/res/layout/fragment_library_rename_shelf.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: App Design, Design

#147 Share of BibTeX file - Feature Adjustment (Bug fix #127)
  BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteTypeLut.java
Labels: Bugfix, Import/Export and Sharing

#151 Fix overlapping note items (see Issue #146)
  BibBuddy/app/src/main/java/de/bibbuddy/ImportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/Note.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteAudioItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteTextItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteTypeLut.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/VoiceNoteEditorFragment.java
Labels: Bugfix

#160 Bugfixes author retrieval & note export
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
Labels: Bugfix, Data, Import/Export and Sharing

#153 Fixes problems with back button (see Issue #140, #123)
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/BackStackFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/Book.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/HelpFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/HomeFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/ImprintFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/VoiceNoteEditorFragment.java
Labels: Bugfix

#156 Code cleanup (see Issue #152)
  BibBuddy/app/src/main/java/de/bibbuddy/ApiReader.java
  BibBuddy/app/src/main/java/de/bibbuddy/Author.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/Book.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/DataValidation.java
  BibBuddy/app/src/main/java/de/bibbuddy/DateConverter.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchItemType.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/Shelf.java
  BibBuddy/app/src/main/java/de/bibbuddy/ShelfDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/ShelfItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/SortCriteria.java
  BibBuddy/app/src/main/java/de/bibbuddy/SortDialog.java
  BibBuddy/app/src/main/java/de/bibbuddy/TagDao.java
Labels: Code Cleanup

#157 Bug Fix (#154): Import of book notes
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/ImportBibTex.java
Labels: Bug, Import/Export and Sharing

#162 Design Rework #6 - Help
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/HelpFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteAudioItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/res/drawable/audionote.png
  BibBuddy/app/src/main/res/drawable/library_nav.png
  BibBuddy/app/src/main/res/drawable/sort_icon.png
  BibBuddy/app/src/main/res/layout/fragment_author.xml
  BibBuddy/app/src/main/res/layout/fragment_book.xml
  BibBuddy/app/src/main/res/layout/fragment_book_notes.xml
  BibBuddy/app/src/main/res/layout/fragment_help.xml
  BibBuddy/app/src/main/res/layout/fragment_library.xml
  BibBuddy/app/src/main/res/layout/fragment_notes.xml
  BibBuddy/app/src/main/res/layout/fragment_search.xml
  BibBuddy/app/src/main/res/layout/list_view_item_book.xml
  BibBuddy/app/src/main/res/values/colors.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: App Design, Bugfix, Search Technology, User Guidance

#164 Cleanup Import, LibraryFragment (see Issue #152)
  BibBuddy/app/src/main/java/de/bibbuddy/BibTexKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/ImportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/UriUtils.java
  BibBuddy/app/src/main/java/de/bibbuddy/UriUtilsKeys.java
Labels: Code Cleanup

#163 Test updates
  BibBuddy/.idea/inspectionProfiles/Project_Default.xml
  BibBuddy/app/build.gradle
  BibBuddy/app/src/androidTest/java/de/bibbuddy/ExampleInstrumentedTest.java
  BibBuddy/app/src/androidTest/java/de/bibbuddy/NotesFragmentTest.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/res/layout/fragment_imprint.xml
  BibBuddy/app/src/main/res/menu/fragment_note_list_menu.xml
  BibBuddy/app/src/test/java/de/bibbuddy/ExampleUnitTest.java
Labels: Bugfix, Code Cleanup, Test

#165 Bug fix search audio
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchItemType.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchModel.java
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Bug

#171 Add screenshots of Bib Buddy
  ScreenshotsWiki/BibImport.png
  ScreenshotsWiki/BibShare.png
  ScreenshotsWiki/Impressum.png
  ScreenshotsWiki/Library.png
  ScreenshotsWiki/LibraryBookAdd.png
  ScreenshotsWiki/LibraryBooks.png
  ScreenshotsWiki/LibraryHelp.png
  ScreenshotsWiki/LibraryNotesScreen.png
  ScreenshotsWiki/Notes.png
  ScreenshotsWiki/Search.png
  ScreenshotsWiki/SearchFilterSort.png
Labels: App Design

#170 Add logging to try catch (see Issue #152)
  BibBuddy/app/src/main/java/de/bibbuddy/ApiReader.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/DataValidation.java
  BibBuddy/app/src/main/java/de/bibbuddy/ExportBibTex.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/ShelfDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/TagDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/UriUtils.java
  BibBuddy/app/src/main/java/de/bibbuddy/VoiceNoteEditorFragment.java
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Code Cleanup

#169 Home Fragment
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/HomeFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/MainActivity.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/res/layout/fragment_home.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: User Guidance

#172 Final clean up note features
  BibBuddy/app/build.gradle
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditor.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorBulletSpan.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorPart.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorQuoteSpan.java
  BibBuddy/app/src/main/java/de/bibbuddy/SeekBarListener.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/VoiceNoteEditorFragment.java
Labels: Code Cleanup

#173 Final clean up API features
  BibBuddy/app/src/main/java/de/bibbuddy/ApiReader.java
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
  README.md
Labels: Code Cleanup

#174 Zotero BibTeX Support
  BibBuddy/app/src/main/java/de/bibbuddy/BibTexKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/ImportBibTex.java
Labels: Import/Export and Sharing
