Repository UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy, pull requests merged in 2021-02, with the labels that each got.

#71 Rename and delete shelf in library
  BibBuddy/app/build.gradle
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRenameShelfFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/ShelfDao.java
  BibBuddy/app/src/main/res/color/library_item_selector.xml
  BibBuddy/app/src/main/res/layout/fragment_library_add_shelf.xml
  BibBuddy/app/src/main/res/layout/fragment_library_delete_shelf.xml
  BibBuddy/app/src/main/res/layout/fragment_library_rename_shelf.xml
  BibBuddy/app/src/main/res/layout/list_view_item_library.xml
  BibBuddy/app/src/main/res/menu/fragment_library_menu.xml
  BibBuddy/app/src/main/res/menu/navigation_menu.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Library

#70 Text editor UI changes
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/res/drawable-xxhdpi/slidebar_arrow_left.png
  BibBuddy/app/src/main/res/drawable-xxhdpi/slidebar_arrow_right.png
  BibBuddy/app/src/main/res/drawable-xxhdpi/strike_through.png
  BibBuddy/app/src/main/res/drawable/arrow_down.png
  BibBuddy/app/src/main/res/drawable/arrow_up.png
  BibBuddy/app/src/main/res/drawable/rounded_border.xml
  BibBuddy/app/src/main/res/drawable/text_format.png
  BibBuddy/app/src/main/res/layout/activity_main.xml
  BibBuddy/app/src/main/res/layout/fragment_home.xml
  BibBuddy/app/src/main/res/layout/fragment_text_note_editor.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: App Design, Multimedia

#75 Create book form (see Issue #21)
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/DataValidation.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryAddShelfFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryRenameShelfFragment.java
  BibBuddy/app/src/main/res/layout/element_author.xml
  BibBuddy/app/src/main/res/layout/fragment_book_form.xml
  BibBuddy/app/src/main/res/menu/add_book_menu.xml
  BibBuddy/app/src/main/res/values/colors.xml
  BibBuddy/app/src/main/res/values/strings.xml
  BibBuddy/app/src/main/res/values/themes.xml
  BibBuddy/app/src/test/java/de/bibbuddy/DataValidationTest.java
Labels: Import/Export and Sharing

#78 Implement API connection
  BibBuddy/.idea/codeStyles/codeStyleConfig.xml
  BibBuddy/app/src/main/AndroidManifest.xml
  BibBuddy/app/src/main/java/de/bibbuddy/ApiReader.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/res/layout/fragment_search.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Data

#73 Bug fix text editor
  BibBuddy/app/src/main/java/de/bibbuddy/MainActivity.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteAudioItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteImageItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/NoteTextItem.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditor.java
  BibBuddy/app/src/main/java/de/bibbuddy/RichTextEditorQuoteSpan.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/res/color/editor_toolbar_selector.xml
  BibBuddy/app/src/main/res/layout/fragment_text_note_editor.xml
  BibBuddy/app/src/main/res/layout/list_view_item_note.xml
  BibBuddy/app/src/main/res/layout/navigation_bar.xml
Labels: App Design, Bug, Multimedia

#72 User manual
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/HelpFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/NotesFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/TextNoteEditorFragment.java
  BibBuddy/app/src/main/res/layout/activity_main.xml
  BibBuddy/app/src/main/res/layout/fragment_book.xml
  BibBuddy/app/src/main/res/layout/fragment_book_notes_view.xml
  BibBuddy/app/src/main/res/layout/fragment_help.xml
  BibBuddy/app/src/main/res/layout/fragment_library.xml
  BibBuddy/app/src/main/res/menu/fragment_book_menu.xml
  BibBuddy/app/src/main/res/menu/fragment_book_note_menu.xml
  BibBuddy/app/src/main/res/menu/fragment_library_menu.xml
  BibBuddy/app/src/main/res/menu/fragment_note_list_menu.xml
  BibBuddy/app/src/main/res/menu/fragment_texteditor_menu.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: User Guidance

#80 Use the API for adding a book
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/SearchFragment.java
  BibBuddy/app/src/main/res/layout/fragment_book_online.xml
  BibBuddy/app/src/main/res/layout/fragment_search.xml
Labels: Data, Library

#74 Barcode scanner (see Issue #11)
  BibBuddy/app/build.gradle
  BibBuddy/app/src/main/AndroidManifest.xml
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/res/layout/fragment_barcode_scanner.xml
  BibBuddy/app/src/main/res/layout/fragment_notes.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Search Technology

#81 Manifest permission for device storage access
  BibBuddy/app/src/main/AndroidManifest.xml
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Import/Export and Sharing

#79 Notes fragment UI test
  BibBuddy/app/build.gradle
  BibBuddy/app/src/androidTest/java/de/bibbuddy/NotesFragmentTest.java
  BibBuddy/app/src/androidTest/java/de/bibbuddy/NotesFragmentUITest.java
  BibBuddy/app/src/main/AndroidManifest.xml
  BibBuddy/app/src/main/java/de/bibbuddy/Note.java
  BibBuddy/app/src/main/res/layout/activity_main.xml
  BibBuddy/app/src/main/res/layout/fragment_notes.xml
  BibBuddy/app/src/main/res/layout/fragment_text_note_editor.xml
Labels: Test

#85 Bugfix: Overlapping views
  BibBuddy/app/src/main/res/layout/fragment_book_form.xml
  BibBuddy/app/src/main/res/layout/fragment_book_notes_view.xml
Labels: Bug

#87 Implement Barcode API connection
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/res/layout/fragment_barcode_scanner.xml
Labels: Library, Search Technology

#91 Manage books and notes (see Issue #82)
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/Book.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookDao.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFormFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesView.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookNotesViewModel.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookRecyclerViewAdapter.java
  BibBuddy/app/src/main/java/de/bibbuddy/DataValidation.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryKeys.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryModel.java
  BibBuddy/app/src/main/res/layout/fragment_book_notes_view.xml
  BibBuddy/app/src/main/res/layout/list_view_item_book.xml
  BibBuddy/app/src/main/res/layout/list_view_item_book_notes_view.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Library

#89 Export of book list as .bib file
  BibBuddy/app/src/main/java/de/bibbuddy/BookFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/LibraryFragment.java
  BibBuddy/app/src/main/res/menu/fragment_book_menu.xml
  BibBuddy/app/src/main/res/values/strings.xml
Labels: Import/Export and Sharing

#93 Implement author API
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorRetriever.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookBarcodeScannerFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/BookOnlineFragment.java
  BibBuddy/app/src/main/java/de/bibbuddy/IsbnRetriever.java
Labels: Data

#95 Update CI Workflow
  .github/workflows/android-release.yml
Labels: Test

#97 Fix bug when adding a new book
  BibBuddy/app/src/main/java/de/bibbuddy/AuthorDao.java
Labels: Bug

#99 Update workflow (upload release apk)
  .github/workflows/android-release.yml
Labels: Test
